from UserProfileViewTest import UserProfileViewTest
from QuestionnaireViewTest import QuestionnaireViewTest
from GraphViewTest import GraphViewTest
from LoginRedirectViewTest import LoginRedirectViewTest